# Generated by Django 3.0 on 2021-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliedcourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_student', models.CharField(max_length=50)),
                ('offline', models.BooleanField(default=None)),
                ('online', models.BooleanField(default=None)),
                ('apply_date', models.DateField(auto_now=True)),
                ('apply_course', models.ManyToManyField(to='home.courses')),
            ],
        ),
    ]
