# Generated by Django 3.0 on 2021-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appliedcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcourses',
            name='offline',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='appliedcourses',
            name='online',
            field=models.BooleanField(),
        ),
    ]
