# Generated by Django 3.0 on 2021-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210602_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcourses',
            name='offline',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedcourses',
            name='online',
            field=models.BooleanField(null=True),
        ),
    ]
